version: '3.8'
services:
  edm-db:
    image: postgres:14-alpine
    container_name: edm-db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./backend
    image: backend-image
    container_name: backend-container
    depends_on:
      edm-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://edm-db:5432/edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

volumes:
  postgres_data: