version: '3.8'
services:
  backend:
    build: ../backend
    image: backend-image
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://edm-db-test:5432/edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_ROOT_ENDPOINT=http://localhost:9000
    restart: always
