version: '3.8'
services:
  edm-db:
    image: postgres:14-alpine
    container_name: edm-db
    ports:
      - "5435:5432"
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z.fips
    container_name: test_minio
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server ~/minio --console-address :9090
    volumes:
      - minio_data:/minio/data
    ports:
      - '9090:9090'
      - '9000:9000'
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  minio_data: