version: '3.8'
services:
  backend:
    build: ../backend
    image: backend-image
    container_name: backend-container
    depends_on:
      edm-db:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://edm-db:5432/edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
