version: '3.8'
services:
  edm-db:
    image: postgres:14-alpine
    container_name: edm-db
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z.fips
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server ~/minio --console-address :9090
    volumes:
      - minio_data:/minio/data
    ports:
      - '9090:9090'
      - '9000:9000'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: moongrail/caselab-backend:latest
    container_name: backend-container
    depends_on:
      edm-db:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://edm-db:5432/edm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_ROOT_USER=minio-user
      - MINIO_ROOT_PASSWORD=minio-password
      - MINIO_ENDPOINT=http://minio:9000
    restart: always

volumes:
  postgres_data:
  minio_data: