name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      java_version: '17'
      java_distribution: 'corretto'
      cache_build_tool: 'maven'
      cache_path: 'backend/pom.xml'
      test_report_path: '**/target/surefire-reports/TEST-*.xml'

