name: Test Workflow

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      java_distribution:
        required: true
        type: string
      cache_build_tool:
        required: false
        type: string
      cache_path:
        required: false
        type: string
      test_report_path:
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version  }}
          distribution: ${{ inputs.java_distribution }}
          cache: ${{ inputs.cache_build_tool }}
          cache-dependency-path: ${{ inputs.cache_path }}

      - name: Run Tests
        run: mvn -f backend/pom.xml clean verify

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: ${{ inputs.test_report_path}}
          detailed_summary: true

